### LOGIN
POST https://untotaled-oxidizable-marlena.ngrok-free.dev/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### DIJKSTRA ROUTE JAKARTA
POST https://untotaled-oxidizable-marlena.ngrok-free.dev/route/dijkstra
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3MDAwMDE0OSwianRpIjoiNjFhZjljMjAtODQ3MC00ZTljLThiODAtYzBjZTRhOGEzMjgxIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJpZCI6NSwicm9sZSI6ImFkbWluIn0sIm5iZiI6MTc3MDAwMDE0OSwiY3NyZiI6ImQ3NjE3YjAyLTExNTctNGUzNi1hYzhhLTZiNTg0OWQyMDdjMiIsImV4cCI6MTc3MDAwMTA0OX0.E4MoLUqNvonBELXteOfJqlSdqlcdFDKDuGeWZT5rk8Q
Content-Type: application/json

{
  "start_lon": 106.8062,
  "start_lat": -6.2555,
  "end_lon": 106.7986,
  "end_lat": -6.2442
}